name: Bug Report
description: File a bug report
title: '🐛 '
labels: [bug]
assignees:
  - graygalaxy
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I agree to follow the Code of Conduct that this project adheres to.
        - label: I have searched the [issue tracker](//github.com/graygalaxy/lofi-fusion/issues) for a bug report that matches the one I want to file, without success.
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        Tell us what you observed...

        - Browser: Chrome / MS Edge / Opera ...
    validations:
      required: true
  - type: input
    attributes:
      label: Relevent URL
      description: Provide the url where the error occoured
      placeholder: https://someurl.this/path
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output (optional)
      description: Please provide any relevant log output.
      placeholder: |
        This will be automatically formatted into code, so no need for backticks.
        Also, please remove unnecessary whitespace.
      render: Shell
  - type: textarea
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: false
