name: Feature request
description: Request an improvement or feature
title: '🔥 '
labels: [enhancement]
assignees:
  - graygalaxy
body:
  - type: markdown
    attributes:
      value: Request a feature that helps to add more functionality or user-experience
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I agree to follow the Code of Conduct that this project adheres to.
        - label: I have searched the [issue tracker](//github.com/graygalaxy/lofi-fusion/issues) for a bug report that matches the one I want to file, without success.
  - type: textarea
    attributes:
      label: Describe the feature
      description: What would like to add as a feature?
      placeholder: Explain the feature in details. You can add checkboxes as tasks.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest how to implement (optional)
      description: If you can think of some way you can apply the feature, please let us know
      placeholder: Give an idea how to apply the feature
